UserDetails addition in awgment-commons
TechsophyOfficial/awgment-commons pull request #13
Opened 2023-03-29 04:28 UTC by denduluriramasaimohanakhil

dev: 
 lint:0
  coverage:85%
utilityAddition:
  lint:0
  coverage:85%

2023-03-29 06:31 UTC, VaibhavTechsophy requested changes
lets discuss

2023-03-29 06:31 UTC, VaibhavTechsophy commented on build.gradle
> +	implementation 'org.springframework.boot:spring-boot-starter-data-mongodb:2.6.6'
do we need mongodb dependency? why?

2023-03-29 06:31 UTC, VaibhavTechsophy commented on src/main/java/com/techsophy/tsf/commons/acl/ACLEvaluatorImpl.java
> +        return   evaluateACL(aclId,tokenUtils.getToken().orElseThrow(), context).getDelete();
throw what?

2023-03-29 06:31 UTC, VaibhavTechsophy commented on src/main/java/com/techsophy/tsf/commons/acl/CommonsApplication.java
> +        UserDetails userDetails =new UserDetails("https://api-gateway.techsophy.com/api");
pls remove this code

2023-03-29 06:31 UTC, VaibhavTechsophy commented on src/main/java/com/techsophy/tsf/commons/user/UserDetails.java
> +            return Optional.ofNullable(((OAuth2User) principal).getName());
why is name being returned as issuer?

2023-03-29 06:31 UTC, VaibhavTechsophy commented on src/main/java/com/techsophy/tsf/commons/user/UserFormDataDefinition.java
> +    private UserData userData;
this does not look complete

2023-03-29 06:31 UTC, VaibhavTechsophy commented on src/test/java/com/techsophy/tsf/commons/utils/TokenUtilsTest.java
>  class TokenUtilsTest
pls rename this file

2023-03-29 09:51 UTC, denduluriramasaimohanakhil commented on build.gradle
> +	implementation 'org.springframework.boot:spring-boot-starter-data-mongodb:2.6.6'
Yes sir removing dependencies

2023-03-29 09:51 UTC, denduluriramasaimohanakhil commented on src/main/java/com/techsophy/tsf/commons/acl/CommonsApplication.java
> +        UserDetails userDetails =new UserDetails("https://api-gateway.techsophy.com/api");
yes removing unwanted code now

2023-03-29 09:52 UTC, denduluriramasaimohanakhil commented on src/main/java/com/techsophy/tsf/commons/user/UserDetails.java
> +            return Optional.ofNullable(((OAuth2User) principal).getName());
Yes renaming to userDetailsTest

2023-03-29 09:53 UTC, denduluriramasaimohanakhil commented on src/test/java/com/techsophy/tsf/commons/utils/TokenUtilsTest.java
>  class TokenUtilsTest
yes renaming

2023-03-30 05:04 UTC, VaibhavTechsophy requested changes
Please review yourself first before raising merge request

2023-03-30 05:04 UTC, VaibhavTechsophy commented on src/main/java/com/techsophy/tsf/commons/user/UserDetails.java
> +            return Optional.ofNullable(((OAuth2User) principal).getName());
why are we returning name for token

2023-03-30 05:04 UTC, VaibhavTechsophy commented on src/main/java/com/techsophy/tsf/commons/user/UserDetails.java
> +                .header(HttpHeaders.AUTHORIZATION,"Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJ2X2NzTUtiOVFsUVpETUg2TXBUdXV1YURtUWstVTQ3bmZjWVZGbFlpLTMwIn0.eyJleHAiOjE2ODAwODMxMjIsImlhd
what is this?

2023-03-30 07:07 UTC, VaibhavTechsophy approved these changes

2023-03-30 07:07 UTC, merged